/**
 * MediatRApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateProductCommand { 
    name?: string | null;
    description?: string | null;
    price?: number;
    isShow?: boolean;
    isCarousel?: boolean;
    categoryId?: number;
}

