/**
 * MediatRApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HomeProduct } from './homeProduct';
import { ProductImageResponse } from './productImageResponse';


export interface HomePageResponse { 
    homeProducts?: Array<HomeProduct> | null;
    carouselImages?: Array<ProductImageResponse> | null;
}

