/**
 * MediatRApi
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductImageResponse } from './productImageResponse';


export interface HomeProduct { 
    id?: number;
    name?: string | null;
    description?: string | null;
    price?: number;
    coverImage?: string | null;
    categoryId?: number;
    productImages?: Array<ProductImageResponse> | null;
}

