/**
 * BasicAuth
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductImageResponse } from './productImageResponse';


export interface ProductResponse { 
    id?: number;
    name?: string | null;
    description?: string | null;
    price?: number;
    isShow?: boolean;
    isCarousel?: boolean;
    categoryId?: number;
    productImages?: Array<ProductImageResponse> | null;
}

