/**
 * BasicAuth
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductImageResponse { 
    id?: number;
    productId?: number;
    fileName?: string | null;
    isCover?: boolean;
    image?: string | null;
}

