/**
 * BasicAuth
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateProductCommand { 
    id?: number;
    name?: string | null;
    description?: string | null;
    price?: number | null;
    isShow?: boolean | null;
    isCarousel?: boolean | null;
    categoryId?: number | null;
}

